(()=>{'use strict';const C=CompassV2,$=id=>document.getElementById(id),fmt=x=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(x);const metric=()=>{try{return JSON.parse(localStorage.getItem('motionc-preferences-v1'))?.unitSystem==='metric';}catch{return false;}};const weightText=x=>fmt(x*(metric()?.45359237:1))+(metric()?' kg':' lb');
function card(id,title,icon,headline,body,evidence,detail){const e=$(id),wasOpen=e.querySelector('details')?.open;e.replaceChildren();const el=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};e.append(el('div',icon,'driver-icon'),el('h2',title),el('h3',headline),el('p',body),el('p',evidence,'evidence'));const d=document.createElement('details');d.append(el('summary','Why this influence?'),el('p',detail));d.open=Boolean(wasOpen);e.append(d);}
function renderCards(s,r){const [m,rec,sup,b]=r.drivers;const mi=m.inputs;card('movementCard','Movement','🚶',!m.available?'No recent walking pattern yet':m.vector.y>0?'Movement adds northward support':m.vector.y<0?'Recorded walking leans southward':'No net movement influence',!m.available?'No walking pattern is represented in this calculation. That does not establish how active you were.':m.vector.y>0?'Your recorded walking adds a northward contribution to the Compass.':m.vector.y<0?'The walking recorded in this window adds a southward contribution under the current Compass rules.':'The recorded walking contributes no net northward or southward pull.',`${mi.walkingDays} walking days · ${fmt(mi.walkingMinutes)} min · ${mi.streakDays}-day streak. Last 14 days.`,'Walking days, recorded minutes and the current streak are considered together. More walking beyond the calculation’s limit does not add further influence.');
 const ri=rec.inputs,partial=!ri.sleepDays||!ri.stressDays,recorded=ri.sleepDays&&ri.stressDays?'sleep and stress':ri.sleepDays?'sleep':'stress';card('recoveryCard','Recovery','🌙',!rec.available?'Recovery is not yet represented':rec.vector.x>0?'Recovery adds an eastward pull':'No eastward pull from recorded recovery',!rec.available?'Sleep and stress are not represented here. No recorded pressure is not evidence about your recovery.':(rec.vector.x>0?`“With Pressure” refers to the eastward contribution from your recorded ${recorded}.`:'The available readings add no eastward pressure.')+(partial?' This reflects only the recorded signal; the other is not represented.':''),`Sleep: ${ri.sleepDays?fmt(ri.sleepAverageHours)+' h average · '+ri.sleepDays+' days':'not recorded'}. Stress: ${ri.stressDays?fmt(ri.stressAverage)+' / 5 · '+ri.stressDays+' days':'not recorded'}. Last 14 days.`,'Pressure has a specific meaning here: the eastward Recovery component calculated from available sleep and stress evidence. Less eastward pressure can move a southward pattern closer to South; it is not automatically a move toward North.');
 const si=sup.inputs,sc=si.components,opposed=sc.hydration.normalized!==null&&sc.lifestyleCombined!==null&&sc.hydration.normalized*sc.lifestyleCombined<0;card('supportCard','Support','💧',!sup.available?'Support is not yet represented':sup.vector.y>0?'Support adds a northward influence':sup.vector.y<0?'Support adds a southward influence':'No net Support influence',!sup.available?'There are no usable hydration or saved Lifestyle inputs for this part of the calculation.':opposed?'Hydration and saved Lifestyle inputs pull in different directions. Together, they '+(sup.vector.y>0?'lean north.':sup.vector.y<0?'lean south.':'offset one another.'):'The available hydration and saved Lifestyle inputs '+(sup.vector.y>0?'add northward support.':sup.vector.y<0?'add a southward contribution.':'add no net directional pull.'),`Hydration: ${si.hydrationDays?fmt(si.hydrationAverageOunces*(metric()?29.5735295625:1))+(metric()?' mL':' oz')+' average · '+si.hydrationDays+' days':'not recorded'}. Latest saved Lifestyle: ${si.lifestyleWeek||'not recorded'}.`,'Hydration uses the last 14 days. Lifestyle uses the latest saved assessment; its date is shown rather than implying it is recent. Only nutrition, alcohol and smoking enter Support. Walking, sleep and stress are counted in their own cards.');
 const bi=b.inputs,w=b.waist,weight=b.weightContribution,combined=b.vector.y;let head=combined>0?'Body Trend adds a northward influence':combined<0?'Body Trend adds a southward influence':'No net Body Trend influence';if(weight===0&&!w.qualified&&bi.weightMeasurements>=2)head='Weight is stable';if(bi.weightMeasurements<2&&!w.qualified)head='Weight trend is not yet established';
 let body=bi.weightInterpretation.replaceAll('Vibratory Zone','goal range').replace('limited South context','a southward caution').replace('; treated as context, not failure','');
 if(w.status==='blocked-below-goal')body=(weight<0?'Weight is still falling below your recorded goal range.':weight===0?'Weight is stable below your recorded goal range.':'Weight is moving toward your goal range but remains below it.')+' Your waist trend shows a decrease, but it adds no northward credit here. '+(weight<0?'Body Trend keeps its southward caution.':'The weight-based contribution is unchanged.');
 else if(w.qualified)body+=' '+C.waistExplanation(b);else if(weight===0&&bi.weightMeasurements>=2)body+=' Stable weight supplies context without pushing the Compass in either direction.';
 const range=bi.vibratoryZone;let ev=`${bi.weightMeasurements} weight readings in 35 days${bi.firstWeight!==null?' · '+weightText(bi.firstWeight)+' → '+weightText(bi.lastWeight):''}. Goal: ${range?(range.low===range.high?weightText(range.low):weightText(range.low)+'–'+weightText(range.high)):'not recorded'}.`;
 if(w.qualified)ev+=` Waist trend: ${w.count} dated observations over ${w.span} days; newest ${w.age} days ago.`;
 card('bodyCard','Body Trend','⚖️',head,body,ev,w.qualified?'Weight and qualifying waist evidence combine within one contribution limit. The newest waist reading cannot amplify the trend beyond the earlier supported rate. Older qualifying evidence gradually has less influence. Lifetime waist progress remains separate.':'Weight direction is interpreted against the recorded goal range. A change within the stability band supplies context without directional force.');
}
window.CompassV2Cards=Object.freeze({render:renderCards});})();