/* Exploration only. All scores, summaries, trends and chart samples are curated.
   Measurement/history values come from the existing central Dave provider. */
const DemoDaily = (() => {
  const display=DEMO_DAILY_DISPLAY;
  let selected=display.manifest.today, month=selected.slice(0,7);
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const metric=(name,value,unit='')=>`<div class="dd-metric"><span>${name}</span><strong>${value===null||value===undefined?'Not recorded':escape(value)} <small>${value===null||value===undefined?'':unit}</small></strong></div>`;
  const labels={sleep:'Sleep quality',hydration:'Hydration',nutrition:'Nutrition',activity:'Activity level',stress:'Stress management',alcohol:'Alcohol',smoking:'Smoking',movement:'Daily movement'};
  const answers={sleep:['Usually sleep less than 6 hours','Usually sleep around 6 hours','Usually sleep 7–8 hours each night'],hydration:['Rarely drink enough water','Drink some water but could improve','Drink enough water most days'],nutrition:['Mostly unhealthy food choices','A mix of healthy and unhealthy choices','Mostly healthy food choices'],activity:['Rarely exercise','Exercise occasionally','Exercise regularly'],stress:['High stress most days','Moderate stress most days','Stress is usually well managed'],alcohol:['High alcohol intake','Moderate alcohol intake','Low alcohol intake'],smoking:['Current smoker','Former smoker','Non-smoker'],movement:['Average under 3,000 steps per day','Average 3,000–8,000 steps per day','Average over 8,000 steps per day']};
  function calendar(){
    const months=Object.keys(display.months),i=months.indexOf(month),m=display.months[month];
    return `<div class="dd-heading"><h2>${m.label}</h2><div class="dd-controls"><button type="button" data-month="${months[i-1]||''}" ${i===0?'disabled':''} aria-label="Previous month">←</button><button type="button" data-today>Demo today</button><button type="button" data-month="${months[i+1]||''}" ${i===months.length-1?'disabled':''} aria-label="Next month">→</button></div></div><p class="dd-muted">Select a dot to explore that saved day. July 27–September 20, 2026.</p><div class="dd-calendar" role="group" aria-label="Dave’s recorded days">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<span class="dd-weekday">${d}</span>`).join('')}${m.cells.map(c=>!c?'<span></span>':c.supported?`<button type="button" data-date="${c.date}" class="dd-calendar-day ${c.date===selected?'is-selected':''}" ${c.date===selected?'aria-current="date"':''} aria-label="${escape(display.snapshots[c.date].label)}, ${display.snapshots[c.date].score.percent} percent, ${display.snapshots[c.date].score.color}"><span>${c.day}</span><i class="dd-dot ${display.snapshots[c.date].score.color}"></i></button>`:`<span class="dd-outside">${c.day}</span>`).join('')}</div><p class="dd-key">Dot colours: <span class="dd-dot green"></span> Green · <span class="dd-dot light-green"></span> Light green · <span class="dd-dot yellow"></span> Yellow · <span class="dd-dot orange"></span> Orange · <span class="dd-dot red"></span> Red</p>`;
  }
  function render(){
    const s=display.snapshots[selected],e=demoSnapshot.state.entries[selected],g=demoSnapshot.state.dailyGauges[selected],p=DEMO_DAVE.profile;
    const root=document.getElementById('demo-root');
    root.innerHTML=`<main class="demo-daily" id="dd-root"><header class="dd-hero"><div><p class="dd-eyebrow">MO-TRIBE · DAVE’S SAVED HISTORY</p><h1>Daily</h1><p>One day. Four standing promises. A routine taking shape.</p></div><div><strong>Dave · Read-only</strong><p id="dd-selected-label">${s.label}</p><small>Demo today: September 20, 2026 · Imperial</small></div></header>
      <section class="dd-card dd-entry"><div class="dd-heading"><div><p class="dd-eyebrow">SAVED CHECK-IN</p><h2>A day in Dave’s routine</h2></div><div class="dd-controls"><label>Date <input id="dd-date" type="date" value="${selected}" min="${display.manifest.start}" max="${display.manifest.end}"></label><button type="button" data-today>Demo today</button></div></div><aside class="dd-reflection"><span>REFLECTION POINT</span><q>${s.reflection}</q></aside><div class="dd-grid">${metric('Weight',e.weight,'lb')}${metric('Walking distance',s.walkTotals.distance,'mi')}${metric('Walking time',s.walkTotals.minutes,'min')}${metric('Average walking HR',s.walkTotals.walkingHr,'bpm')}${metric('Steps',s.walkTotals.steps)}${metric('Resting HR',e.restingHr,'bpm')}</div>
      <details><summary>About these measurements</summary><p>Steps and walking HR shown here were recorded in Dave’s fictional history. Missing readings stay unrecorded; a recorded rest day has no walks.</p></details><h3>Saved walks</h3>${e.walks.length?`<div class="dd-walks">${e.walks.map((w,i)=>`<article class="dd-walk"><strong>Walk ${i+1}</strong><span>${escape(w.distance)} mi</span><span>${w.minutes} min</span><span>${w.steps} steps</span><span>${w.walkingHr} bpm</span></article>`).join('')}</div>`:'<p class="dd-rest">Recorded rest day · No walks recorded.</p>'}<h3>Standing promises</h3><div class="dd-promises">${[['noRestaurant','No restaurant meal'],['noAlcohol','No Alcohol'],['noJunkFood','Skipped Junk Food'],['smokeFreeDay','Smoke Free Day']].map(([k,t])=>`<div><b aria-label="${e[k]?'Met':'Not met'}">${e[k]?'✓':'✕'}</b>${t}</div>`).join('')}</div><h3>Observation</h3><p class="dd-observation">${escape(e.note||'No observation recorded for this day.')}</p><p class="dd-muted">Fictional data · Read-only · Nothing here affects your account</p></section>
      <section class="dd-card dd-score"><div><p class="dd-eyebrow">DAILY HEALTH SCORE</p><h2>${s.score.percent}%</h2><p>${s.score.color.replace('-',' ')} · ${s.score.total}/${s.score.maximum} assessed points</p></div><button type="button" class="dd-orb ${s.score.color}" data-score aria-label="Open score explanation: ${s.score.percent} percent">${s.score.percent}%</button><button type="button" data-score>Why this colour?</button></section>
      <section class="dd-card"><div class="dd-heading"><h2>Daily gauges</h2><details class="dd-info"><summary>How to read the signals</summary><p>The light shows the previous seven completed days. Sleep: green 7+ hours, yellow 6–6.99, orange 5–5.99, red below 5. Stress: green up to 1, yellow over 1–2, orange over 2–3, red over 3–4, deep red over 4. Hydration has no status light.</p><p>Sleep’s arrow compares two blocks of three completed days. Stress and hydration compare the selected day with yesterday. ↓ means improvement; ↑ means decline or increase. The arrow never overrides the light.</p></details></div><div class="dd-gauges">${['hydration','stress','sleep'].map(k=>{const v=g[k]?.value,a=s.gauges[k],unit=k==='hydration'?'oz':k==='sleep'?'hours':'of 5';return `<article class="dd-gauge ${k}"><h3>${k[0].toUpperCase()+k.slice(1)}</h3><strong class="dd-reading">${v??'—'} <small>${unit}</small></strong><div class="dd-tube" role="img" aria-label="${k}: ${v??'not recorded'} ${v===undefined?'':unit}"><span data-fill="${a.fill}"></span></div><p class="dd-muted">${v===undefined?'Not recorded':'Recorded for '+selected}</p>${a.average?`<p class="dd-signal"><i class="${a.average.color}"></i>${a.average.label}</p>`:''}<p class="dd-signal"><b>${a.trend.arrow}</b>${a.trend.label}</p><details class="dd-chart"><summary>Previous 7 completed days</summary>${a.chart}</details></article>`;}).join('')}</div>${s.insights.length?`<div class="dd-messages"><h3>Message for this day</h3>${s.insights.map(m=>`<p>${m}</p>`).join('')}</div>`:''}</section>
      <section class="dd-card" id="dd-calendar-host">${calendar()}</section>
      <section class="dd-card"><div class="dd-heading"><h2>Week of this entry</h2><strong>${s.weekRange}</strong></div><p class="dd-muted">Sunday–Saturday · Recorded evidence through ${selected}. This calendar week differs from Summary’s rolling seven days.</p><div class="dd-weekly-stats">${s.weeklyStats}</div><details open><summary>Notes from this week</summary>${s.weeklyNotes}</details><details><summary>Previous weeks</summary>${s.previousWeeks}</details></section>
      <section class="dd-card"><h2>Search Dave’s observations</h2><label>Search saved notes <input id="dd-search" type="search" placeholder="Try rest, split, or café" autocomplete="off"></label><p class="dd-muted">Search all 56 supported days. Selecting a result opens that day.</p><div id="dd-search-results" aria-live="polite"></div></section>
      <section class="dd-card"><div class="dd-heading"><h2>Milestones</h2><span>${s.milestoneCount}</span></div><p class="dd-muted">As of ${selected}</p><div class="dd-progress">${s.progress}${s.walkAverage}</div><div class="dd-milestones">${s.milestones}</div></section>
      <section class="dd-card"><h2>Dave’s check-in</h2><p class="dd-muted">Weekly check-in recorded · ${s.weekKey} week · Read-only</p><details><summary>Personal details and measurements</summary><div class="dd-grid">${metric('Age',p.age)}${metric('Sex','Male')}${metric('Height',p.heightInches,'in')}${metric('Starting weight',p.startWeight,'lb')}${metric('Starting waist',p.startingWaist,'in')}${metric('Waist at this date',s.waist,'in')}${metric('Waist change',s.waistChange,'in')}</div><p>Waist readings use the latest recorded measurement available by this date.</p></details><details><summary>Weekly Lifestyle · ${s.weeklyScore}/24</summary><dl class="dd-lifestyle">${Object.entries(labels).map(([k,label])=>`<div><dt>${label}</dt><dd>${answers[k][s.weeklyValues[k]-1]}</dd></div>`).join('')}</dl></details><details><summary>Goals</summary><div class="dd-grid">${metric('Real goal',p.realGoal,'lb')}${metric('Motivational goal',p.motivationalGoal,'lb')}${metric('Intended Vibratory Zone',p.realGoal+'–'+demoSnapshot.state.profile.vibratoryLine,'lb')}</div></details></section>
      <section class="dd-card"><h2>Scratch Pad</h2><p>No Scratch Pad notes are included in Dave’s Demo history.</p><p class="dd-muted">Read-only · His recorded observations are available above.</p></section>
      <dialog id="dd-score-dialog" aria-labelledby="dd-score-title"><button type="button" data-close class="dd-close" aria-label="Close explanation">Close</button><h2 id="dd-score-title">Daily Dot explanation</h2>${s.explanation}</dialog></main>`;
    const host=root.querySelector('.demo-daily');
    host.querySelectorAll('[data-fill]').forEach(node=>{node.style.height=node.dataset.fill+'%';});
    host.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-today'))select(display.manifest.today);else if(b.dataset.date)select(b.dataset.date);else if(b.dataset.month&&Object.hasOwn(display.months,b.dataset.month)){month=b.dataset.month;host.querySelector('#dd-calendar-host').innerHTML=calendar();}else if(b.hasAttribute('data-score'))host.querySelector('dialog').showModal();else if(b.hasAttribute('data-close'))host.querySelector('dialog').close();});
    host.querySelector('#dd-date').addEventListener('change',event=>{if(Object.hasOwn(display.snapshots,event.target.value))select(event.target.value);else event.target.value=selected;});
    host.querySelector('#dd-search').addEventListener('input',event=>search(event.target.value));
    search('');
  }
  function select(date){if(!Object.hasOwn(display.snapshots,date))return;selected=date;month=date.slice(0,7);render();const input=document.getElementById('dd-date');input.focus({preventScroll:true});document.getElementById('dd-root').scrollIntoView({block:'start'});}
  function search(query){const q=query.trim().toLocaleLowerCase();const matches=display.dates.filter(d=>{const note=demoSnapshot.state.entries[d].note;return note&&(!q||(d+' '+display.snapshots[d].label+' '+note).toLocaleLowerCase().includes(q));});document.getElementById('dd-search-results').innerHTML=`<p>${matches.length} observation${matches.length===1?'':'s'}</p><div class="dd-results">${matches.map(d=>`<button type="button" data-date="${d}"><strong>${display.snapshots[d].label}</strong><span>${escape(demoSnapshot.state.entries[d].note)}</span></button>`).join('')||'<p>No matching observations.</p>'}</div>`;}
  return Object.freeze({render});
})();
