/* Run from any working directory: node demo/build.mjs
   Emits one protected Function document; never emits a public frame HTML file. */
import fs from 'node:fs';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8').replace(/\r\n/g,'\n');
const hash=s=>crypto.createHash('sha256').update(s).digest('base64');
// Curated Daily outputs must be revalidated offline when their sources change.
const dailyDisplay=JSON.parse(read('demo/foundation/daily-display.js').match(/demoFreeze\(([\s\S]*)\);/)[1]);
for(const [file,expected] of [['demo/foundation/dave.js',dailyDisplay.manifest.sourceSha256],['daily/script.js',dailyDisplay.manifest.productionRulesSha256]]) {
 const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
 if(actual!==expected)throw Error('Revalidate curated Demo Daily outputs before building: '+file);
}
if(dailyDisplay.dates.length!==56||dailyDisplay.dates.some(date=>!dailyDisplay.snapshots[date]))throw Error('Incomplete curated Daily history');
const compassDisplay=JSON.parse(read('demo/foundation/compass-display.js').match(/demoFreeze\(([\s\S]*)\);/)[1]);
for(const [file,expected] of Object.entries(compassDisplay.manifest.sourceHashes)) {
 if(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')!==expected)throw Error('Revalidate curated Demo Compass outputs before building: '+file);
}
if(compassDisplay.history.length!==14||compassDisplay.manifest.asOf!=='2026-09-20'||compassDisplay.history.some((p,i)=>p.date!==new Date(Date.UTC(2026,8,7+i)).toISOString().slice(0,10)))throw Error('Incomplete curated Compass history');
const parts=['dave.js','summary-rules.js','compass-engine.js','provider.js','summary-template.js','summary-view.js','daily-display.js','daily-view.js','compass-display.js','compass-view.js','renderer.js'];
const script="'use strict';\n(()=>{\n"+parts.map(p=>read('demo/foundation/'+p)).join('\n')+'\n})();';
if(script.includes('</script'))throw Error('Unexpected script terminator');
const style=read('demo/foundation/summary.css')+'\n'+read('demo/foundation/daily.css')+'\n'+read('demo/foundation/compass.css');
const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>MotionC Demo — Dave’s Summary</title><style>'+style+'</style></head><body><div class="demo-banner"><strong>DEMO MODE</strong>Dave is fictional · Read-only<p id="demo-connection">Fixed demonstration date: September 20, 2026</p></div><div id="demo-root"></div><script>'+script+'</script></body></html>';
const policy="default-src 'none'; base-uri 'none'; object-src 'none'; connect-src 'none'; form-action 'none'; worker-src 'none'; img-src 'none'; font-src 'none'; media-src 'none'; manifest-src 'none'; style-src 'sha256-"+hash(style)+"'; script-src 'sha256-"+hash(script)+"'; frame-src 'none'; frame-ancestors 'self'; sandbox allow-scripts";
const headers={'Content-Security-Policy':policy,'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex, nofollow, noarchive','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()','Content-Type':'text/html; charset=utf-8'};
const output='// Generated by demo/build.mjs. Edit Demo foundation sources, then rebuild.\nconst FRAME_HTML = '+JSON.stringify(html)+';\nconst FRAME_HEADERS = Object.freeze('+JSON.stringify(headers,null,2)+');\nexport default {\n fetch(request) {\n  const headers = new Headers(FRAME_HEADERS);\n  if (request.method !== "GET" && request.method !== "HEAD") {\n   headers.set("Allow", "GET, HEAD");\n   return new Response(null, {status:405,headers});\n  }\n  return new Response(request.method === "HEAD" ? null : FRAME_HTML,{status:200,headers});\n }\n};\n';
fs.writeFileSync(path.join(root,'api/demo-frame.js'),output);
// Change only Demo content hashes; all restrictive directives and routes survive.
const config=JSON.parse(read('vercel.json'));
const shell=read('demo/index.html');
const shellStyle=shell.match(/<style>([\s\S]*?)<\/style>/)[1],shellScript=shell.match(/<script>([\s\S]*?)<\/script>/)[1];
for(const rule of config.headers.filter(r=>r.source.startsWith('/demo'))){
 for(const header of rule.headers){if(header.key!=='Content-Security-Policy')continue;
  header.value=rule.source==='/demo/frame.html'?policy:header.value.replace(/style-src 'sha256-[^']+'/,'style-src \'sha256-'+hash(shellStyle)+"'").replace(/script-src 'sha256-[^']+'/,'script-src \'sha256-'+hash(shellScript)+"'");
 }
}
fs.writeFileSync(path.join(root,'vercel.json'),JSON.stringify(config,null,2)+'\n');
console.log('Built protected Demo function and refreshed exact content hashes.');
